name: fe_project
description: "fe app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0  # fl_chartを追加
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  share_plus: ^10.0.3
  vibration: ^2.0.1
  firebase_remote_config: ^5.1.3
  flutter_launcher_icons: "^0.14.1"
  audioplayers: ^6.1.0
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.1
  flutter_staggered_animations: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/fe_icon1.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/icons/fe_icon_foreground.png"
flutter_native_splash:
  color: '#ffffff'
  image: 'assets/icons/fe_splash.png'
  color_dark: '#262626'
  image_dark: 'assets/icons/fe_icon1.png'
  fullscreen: true
  android_12:
    icon_background_color: '#add8e6'
    image: 'assets/icons/fe_icon1.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/icons/fe_icon1.png'
flutter:
  uses-material-design: true
  assets:
    - assets/audios/correct.mp3
    - assets/audios/cuin.mp3
